name: Deploy kafka-cli

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select GCP environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
      aiven-secret:
        description: Aiven secret to mount, e.g aiven-fullmakter-6rxv2sxp
        required: true

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  POOL: nav-${{ github.event.inputs.environment }}
  SECRET: ${{ github.event.inputs.aiven-secret }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy til ${{ github.event.inputs.environment }}-gcp
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:kafka-cli"
          push: true
          tags: ${{env.IMAGE}},ghcr.io/navikt/${{ github.repository }}:latest

      - uses: nais/deploy/actions/deploy@v1
        env:
          RESOURCE: .nais/kafka-cli.yml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          PRINT_PAYLOAD: true
          CLUSTER: ${{ github.event.inputs.environment }}-gcp
          VAR: pool=${{ env.POOL }},secret=${{ env.SECRET }}
