name: Deploy kafka-manager

on:
  push:
    branches:
      - 'main'
    paths:
      - '.nais/kafka-manager-dev.yml'
      - '.nais/kafka-manager-prod.yml'
      - '.github/workflows/kafka-manager.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Apply to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          RESOURCE: .nais/org-kafka-manager-dev.yml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp

      - name: Apply to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          RESOURCE: .nais/org-kafka-manager-prod.yml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp